// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lqlvkyuyrwsmstooqbed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxbHZreXV5cndzbXN0b29xYmVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTAwMTksImV4cCI6MjA2OTEyNjAxOX0.i3JDlA4_a65Mh0anLTCmYxnuyIJYpNNTWPXyhwIHOlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);